language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.1
otp_release:
  - '20.0'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

env:
  global:
    - MIX_ENV=test

script:
  - mix compile --warnings-as-errors --force
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls

